// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgylviimdnlcftivmqhw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBneWx2aWltZG5sY2Z0aXZtcWh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NjE3MjMsImV4cCI6MjA1OTQzNzcyM30.L1P_8B-PYOnxhYp7q-mUW94PGxWbD3qUGhROeSWoicA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);